# from maze_dataset import SolvedMaze


class TokenError(ValueError):
	"""error for tokenization"""

	pass
